Caution_sync_batch_size
heron-data/docs pull request #11
Opened 2022-05-11 20:27 UTC by JohannesJJ91

* Make call-out on max batch size more clearly visibly

2022-05-11 22:46 UTC, dominickwok requested changes

2022-05-11 22:46 UTC, dominickwok commented on docs/use-cases/beautiful-transactions.md
> +    1. For this use case, please ****
is there missing text here?

2022-05-12 07:57 UTC, JohannesJJ91 commented on docs/use-cases/beautiful-transactions.md
> +    1. For this use case, please ****
Yes, fixed with additional commit. thanks

2022-05-12 08:05 UTC, dominickwok approved these changes

2022-05-12 09:20 UTC, merged